[package]
name = "rsync"
version = "0.1.0"
edition = "2021"
authors = ["Bartols"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10.0"
